# Generated by Django 2.1.15 on 2020-06-04 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dimbussinesdev',
            fields=[
                ('idbussinsedev', models.IntegerField(db_column='IdBussinseDev', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('surname', models.CharField(db_column='Surname', max_length=50)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
            ],
            options={
                'db_table': 'DimBussinesDev',
            },
        ),
        migrations.CreateModel(
            name='Dimclient',
            fields=[
                ('accnumber', models.IntegerField(db_column='AccNumber', primary_key=True, serialize=False)),
                ('clientname', models.CharField(db_column='ClientName', max_length=50)),
                ('salesgroup', models.CharField(db_column='SalesGroup', max_length=50)),
                ('internationalbg', models.CharField(db_column='InternationalBG', max_length=50)),
                ('contactperson', models.CharField(blank=True, db_column='ContactPerson', max_length=50, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
                ('warrantybuyout', models.CharField(blank=True, db_column='WarrantyBuyout', max_length=50, null=True)),
                ('currency', models.CharField(db_column='Currency', max_length=50)),
                ('idbussinesdev', models.ForeignKey(db_column='IdBussinesDev', on_delete=django.db.models.deletion.DO_NOTHING, to='quality.Dimbussinesdev')),
            ],
            options={
                'db_table': 'DimClient',
            },
        ),
    ]
